language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: wNRA+LQ13Wlr66yJsZ2f5sSpH4EN3ygyxWERnljCYBVV5AgSDIE/F20qCbD8388avhz+7p4gQG31ZkfP4RnG+hvxukQPqbZAXZMKHc/qcnYVIVVK/l2MqCEwtAJ/3LmhJGqw8aG1io3RrHhcQGSt+wVbRQnWkPrLXIRfYJQzmh130ED8kqdGVSmNHmqXff+Oo2eanYfDYwtCmA89GSD3COgQgab0L2P8iI2CY8iSWWbMaqvZUelPZE3dZ9oGPdKGJD455V/+I/Gaf6RP3JTMZT3op2U2E4/z/mkukdLtQ+ZA/FNUqk6Z6DDFSRGLicFg7A6/Ys0r1yG3nj9kVegskhx9Z1H3tN7XuKr8/rlUbd0CUU34Tjml8ngIVGL75WuPRr2S8C9NXzzTHDgDg2WCtPaB1vnKDqnOrRkZcLAmLiwxRdbL0lsmEsghayj/S4+45ZmufNRa15zHAY/clwA2NZcL8s85I9dtIhl52n+ocW4Vuxn39qJowwVjNiXsXycyigCGxFlIBp/NHUo2xK9fVaoifUSkiFwXpJ5sk6EEp9Az52iAXtn8h98UheSNLdOpPz0mxNCBsjRQSw+02ETqJR4INYw1iqg/xUrnSG0+QEgD9Rz7Cj09iqAHMvS8CWbjFpVVdJS+yqaSz4YqL9IngFduH9lFFgyUzM3yI7c3i3A=
  app: https://pure-coast-65335.herokuapp.com/
  on:
    repo: katiewest820/blog-app-mongoose-challenge-solution
