language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: LxgAM2X25fCvpWSWje1M4Qgb7FKb2HC0awhcJhy2kaVolE3lqU00+CbOnvGYkN6ZYybkUq+MHZWEZzOMSJjnyrlHeIq8+GE/Tz44NWNmuW6V6I6cFaMWQD5+IeZ96KWwrP8lcPDECDhc/mZSFYdezAA5HJycJMdn0jK4pG/61rZpKmlabuZzrCN/WL/NrrjD0DzaoEyQVdqmd+/crB7porFbhVZ3R54CQvLae6am7ZPDhE80Mr5qk+mmnrX8qknLeWHNSDlk1KJlDEPkcFgNCw6VuA5yB056kw+B9YyEMYULdSJ5V5JerPDu/pckxUXty2XkAUtrtTtKnti4gNNyJAG+0ILFDOysqlCpTaHPXHQMrZyybkCgcpvebAfqqhUSuUjwMIdIMxvQy2f1QOJvk/3xzhhKPC7dCSbUL1PwKUU1Zz0/4Eesj744O1Oy/b5BuysIAW837JzkoCqSLYUt1TH2IrZOVi2LKyFUJ6Ok+ksSAH72TNI323aNGmE2YhN+cpURaIWG61JKh9uMiPr7FcZ+YfsbgcUZkR5VuWVnUssCCfdkfPJo7NxUW5pVC1AWFPtORVHVhTx1pN2UsBCxb/hUPV4nZma8gjTCI1nQyB12NBA0c6pzs6N6g/RTPTnsPAElZdaYsLGDvykiJrP91ZV1fN4YjhCcRGTU6gXBVvc=
  app: blog-app-mongoose-challenge-solution
  on:
    repo: katiewest820/blog-app-mongoose-challenge-solution
